### ISSUE TITLE
what the 'fast' mean?

### ISSUE THREAD

**Issue by Joevaen** [YaoZhang93/FLARE2021-Baseline#1]
Hi,
Could you please tell me what the 'fast' in 'cpu low and fast' mean? Training more quickly or predicting more quickly? 
Thanks.

**Comment by YaoZhang93** [comment]
Hi Joevaen,

The 'fast' means predicting more quickly here. In FLRARE21 Challenge, the inference running time of the model will be evaluated as a metric for final ranking.

You may refer to the details of evaluation:
https://flare.grand-challenge.org/Evaluation/
and the implementation:
https://github.com/JunMa11/FLARE2021/tree/main/Evaluation
for more details.

Thanks,
Yao

**Comment by Joevaen** [comment]
Hi Yao,
that's an awesome job which you guys did. I am not around PC so that it is not convenient to slide into the code.Just have a short chat. 
So, could you please tell me how you make the inference time shorter? I did have used TRT to speedup but failed and use cupy to accelerate the interpolate time. Did you accelerate the process of pure prediction? I am very curious about the method!
Thanks,
Joevaen.

**Comment by YaoZhang93** [comment]
Hi Joevaen,

Thanks for your recognition. The purpose of FLARE21 is to encourage the participants to consider both computation feasibility and performance when design a method in clinical practice. This repository is a baseline for the participants to easily build a framework for the task. We also provide a [list](https://docs.qq.com/sheet/DVVhpeFhNblBiREVO?tab=BB08J2) of other light-weight models.

From my personal perspective, the acceleration may come from but is not limited to the following 3 aspects:
1) **Model**. Abundant real-time methods have been proposed for both natural and medical image segmentation. Please refer to the [list](https://docs.qq.com/sheet/DVVhpeFhNblBiREVO?tab=BB08J2)
2) **Computation**. Some library enables an acceleration of computation, such as TensorRT and CuPy as you mentioned above.
3) **Data**. One can reduce the size of input data by, for example, downsampling and consequently improve the performance. It may raise an issue of trade-off between efficiency and performance.

We encourage the participants to show their innovation on this issue. Notably, you'd better check whether your design is allowed by the rules and is compatible with the evaluation environment of FLARE21 Challenge.

Good Luck,
Yao
